stages:
  - build
  - test
  - deploy
  
build_job:
  stage: build
  script: "bazel build ..."
  script: ANDROID_HOME=/usr/lib/android-sdk/ ./NeVA_android_app/gradlew --build-cache --parallel --project-cache-dir=/tmp/.gradle --build-file=NeVA_android_app/build.gradle -PbuildDir=/tmp/ assembleDebug

test_job:
  stage: test
  script: "bazel test ..."

deploy_job:
  stage: deploy
  script: "/bin/bash deploy.sh"
  only:
    - master

iostest:
  stage: test
  before_script:
    - (cd dependencies/ios/grpc-swift && swift package resolve && swift package update)
    - (cd ios/NeVA/ && carthage update --cache-builds --platform iOS)
  script:
    - xcodebuild clean -project ios/NeVA/NeVA.xcodeproj -scheme NeVA | xcpretty 
    - set -o pipefail && xcodebuild test -project ios/NeVA/NeVA.xcodeproj -scheme NeVA -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 8' | xcpretty -s
  cache:
    paths:
    - ios/NeVA/Carthage
  tags:
    - ios
  only:
    - /^.*ios-.*$/
