stages:
  - build
  - test

job1:
  stage: build
  script: "bazel build :hello-world"
  
jobdeneme:
  stage: build
  script: "echo iosrunner"
  only:
    - /^ios*$/
  tags:
    - ios

job2:
  stage: test
  script: "bazel test :hello-world-test"
