#!/bin/sh
### BEGIN INIT INFO
# Provides:          neva
# Required-Start:    $remote_fs $syslog $network $local_fs $time
# Required-Stop:    $remote_fs $syslog $network $local_fs $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the NeVA backend server.
# Description:       Controls the NeVA backend server.
#   This script will manage NeVA backend server.
### END INIT INFO

PIDFILE="/var/run/neva_backend.pid"
ARGS="--flagfile=/var/NeVA/prod.flags"
BINARY="/var/NeVA/neva_backend"

if [ -f /etc/default/rcS ]; then
  . /etc/default/rcS
fi
. /lib/lsb/init-functions

case "${1:-''}" in
  'start')
    $BINARY $ARGS &
    echo -n $! > $PIDFILE
    log_daemon_msg "Started server."
    ;;

  'stop')
    if [ -f $PIDFILE ];
    then
      pid=$(cat $PIDFILE)
      kill -0 $pid && kill -9 $pid && echo "Stopped server."
    fi
    ;;

  'restart')
    if [ -f $PIDFILE ];
    then
      pid=$(cat $PIDFILE)
      kill -0 $pid && kill -9 $pid && echo "Killed server."
    fi
    $BINARY $ARGS &
    echo -n $! > $PIDFILE
    log_daemon_msg "Restarted server."
    ;;
esac

exit 0
