#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          neva
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the NeVA backend server.
# Description:       Controls the NeVA backend server.
### END INIT INFO
#

case "${1:-''}" in
  'start')
    killall neva_backend
    /var/NeVA/neva_backend >> /var/log/neva_backend.log &
        ;;

  'stop')
    killall neva_backend
        ;;

  'restart')
    killall neva_backend
    /var/NeVA/neva_backend >> /var/log/neva_backend.log &
        ;;

  'setup')
    mkdir /var/NeVA
    touch /var/log/neva_backend.log
    touch /var/run/neva_backend.pid
    chown gitlab-runner:gitlab-runner /var/NeVA
    chown gitlab-runner:gitlab-runner /var/log/neva_backend.log
    chown gitlab-runner:gitlab-runner /var/run/neva_backend.pid
esac

exit 0
