package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
    name = "backend_proto",
    protos = ["backend.proto"],
    with_grpc = True,
)
