# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/suggestion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/suggestion.proto',
  package='neva.backend',
  syntax='proto3',
  serialized_pb=_b('\n\x17protos/suggestion.proto\x12\x0cneva.backend\"\xdc\x01\n\nSuggestion\x12H\n\x13suggestion_category\x18\x01 \x01(\x0e\x32+.neva.backend.Suggestion.SuggestionCategory\x12\x14\n\x0csuggestee_id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1f\n\x04tags\x18\x04 \x03(\x0b\x32\x11.neva.backend.Tag\"?\n\x12SuggestionCategory\x12\x1f\n\x1bINVALID_SUGGESTION_CATEGORY\x10\x00\x12\x08\n\x04MEAL\x10\x01\"C\n\x0eSuggestionList\x12\x31\n\x0fsuggestion_list\x18\x01 \x03(\x0b\x32\x18.neva.backend.Suggestion\"\x1f\n\x03Tag\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
)



_SUGGESTION_SUGGESTIONCATEGORY = _descriptor.EnumDescriptor(
  name='SuggestionCategory',
  full_name='neva.backend.Suggestion.SuggestionCategory',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_SUGGESTION_CATEGORY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEAL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=199,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_SUGGESTION_SUGGESTIONCATEGORY)


_SUGGESTION = _descriptor.Descriptor(
  name='Suggestion',
  full_name='neva.backend.Suggestion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suggestion_category', full_name='neva.backend.Suggestion.suggestion_category', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suggestee_id', full_name='neva.backend.Suggestion.suggestee_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='neva.backend.Suggestion.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='neva.backend.Suggestion.tags', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUGGESTION_SUGGESTIONCATEGORY,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=262,
)


_SUGGESTIONLIST = _descriptor.Descriptor(
  name='SuggestionList',
  full_name='neva.backend.SuggestionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suggestion_list', full_name='neva.backend.SuggestionList.suggestion_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=331,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='neva.backend.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='neva.backend.Tag.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='neva.backend.Tag.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=364,
)

_SUGGESTION.fields_by_name['suggestion_category'].enum_type = _SUGGESTION_SUGGESTIONCATEGORY
_SUGGESTION.fields_by_name['tags'].message_type = _TAG
_SUGGESTION_SUGGESTIONCATEGORY.containing_type = _SUGGESTION
_SUGGESTIONLIST.fields_by_name['suggestion_list'].message_type = _SUGGESTION
DESCRIPTOR.message_types_by_name['Suggestion'] = _SUGGESTION
DESCRIPTOR.message_types_by_name['SuggestionList'] = _SUGGESTIONLIST
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Suggestion = _reflection.GeneratedProtocolMessageType('Suggestion', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTION,
  __module__ = 'protos.suggestion_pb2'
  # @@protoc_insertion_point(class_scope:neva.backend.Suggestion)
  ))
_sym_db.RegisterMessage(Suggestion)

SuggestionList = _reflection.GeneratedProtocolMessageType('SuggestionList', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTIONLIST,
  __module__ = 'protos.suggestion_pb2'
  # @@protoc_insertion_point(class_scope:neva.backend.SuggestionList)
  ))
_sym_db.RegisterMessage(SuggestionList)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'protos.suggestion_pb2'
  # @@protoc_insertion_point(class_scope:neva.backend.Tag)
  ))
_sym_db.RegisterMessage(Tag)


# @@protoc_insertion_point(module_scope)
