# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user_history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import util_pb2 as protos_dot_util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/user_history.proto',
  package='neva.backend',
  syntax='proto3',
  serialized_pb=_b('\n\x19protos/user_history.proto\x12\x0cneva.backend\x1a\x11protos/util.proto\"\x87\x01\n\x06\x43hoice\x12\x14\n\x0csuggestee_id\x18\x01 \x01(\r\x12/\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1c.neva.backend.util.Timestamp\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x11\n\tchoice_id\x18\x05 \x01(\r\"E\n\x0bUserHistory\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12%\n\x07history\x18\x02 \x03(\x0b\x32\x14.neva.backend.Choice\"\xac\x01\n\x0cUserFeedback\x12$\n\x06\x63hoice\x18\x01 \x01(\x0b\x32\x14.neva.backend.Choice\x12\x35\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x01(\x0e\x32#.neva.backend.UserFeedback.Feedback\x12\x0f\n\x07user_id\x18\x03 \x01(\r\".\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x44ISLIKE\x10\x01\x12\x08\n\x04LIKE\x10\x02\x62\x06proto3')
  ,
  dependencies=[protos_dot_util__pb2.DESCRIPTOR,])



_USERFEEDBACK_FEEDBACK = _descriptor.EnumDescriptor(
  name='Feedback',
  full_name='neva.backend.UserFeedback.Feedback',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISLIKE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIKE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=398,
  serialized_end=444,
)
_sym_db.RegisterEnumDescriptor(_USERFEEDBACK_FEEDBACK)


_CHOICE = _descriptor.Descriptor(
  name='Choice',
  full_name='neva.backend.Choice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suggestee_id', full_name='neva.backend.Choice.suggestee_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='neva.backend.Choice.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='neva.backend.Choice.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='neva.backend.Choice.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='choice_id', full_name='neva.backend.Choice.choice_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=198,
)


_USERHISTORY = _descriptor.Descriptor(
  name='UserHistory',
  full_name='neva.backend.UserHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='neva.backend.UserHistory.user_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='history', full_name='neva.backend.UserHistory.history', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=269,
)


_USERFEEDBACK = _descriptor.Descriptor(
  name='UserFeedback',
  full_name='neva.backend.UserFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='choice', full_name='neva.backend.UserFeedback.choice', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='neva.backend.UserFeedback.feedback', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='neva.backend.UserFeedback.user_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERFEEDBACK_FEEDBACK,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=444,
)

_CHOICE.fields_by_name['timestamp'].message_type = protos_dot_util__pb2._TIMESTAMP
_USERHISTORY.fields_by_name['history'].message_type = _CHOICE
_USERFEEDBACK.fields_by_name['choice'].message_type = _CHOICE
_USERFEEDBACK.fields_by_name['feedback'].enum_type = _USERFEEDBACK_FEEDBACK
_USERFEEDBACK_FEEDBACK.containing_type = _USERFEEDBACK
DESCRIPTOR.message_types_by_name['Choice'] = _CHOICE
DESCRIPTOR.message_types_by_name['UserHistory'] = _USERHISTORY
DESCRIPTOR.message_types_by_name['UserFeedback'] = _USERFEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Choice = _reflection.GeneratedProtocolMessageType('Choice', (_message.Message,), dict(
  DESCRIPTOR = _CHOICE,
  __module__ = 'protos.user_history_pb2'
  # @@protoc_insertion_point(class_scope:neva.backend.Choice)
  ))
_sym_db.RegisterMessage(Choice)

UserHistory = _reflection.GeneratedProtocolMessageType('UserHistory', (_message.Message,), dict(
  DESCRIPTOR = _USERHISTORY,
  __module__ = 'protos.user_history_pb2'
  # @@protoc_insertion_point(class_scope:neva.backend.UserHistory)
  ))
_sym_db.RegisterMessage(UserHistory)

UserFeedback = _reflection.GeneratedProtocolMessageType('UserFeedback', (_message.Message,), dict(
  DESCRIPTOR = _USERFEEDBACK,
  __module__ = 'protos.user_history_pb2'
  # @@protoc_insertion_point(class_scope:neva.backend.UserFeedback)
  ))
_sym_db.RegisterMessage(UserFeedback)


# @@protoc_insertion_point(module_scope)
